// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: key_file.proto

package com.google.android.apps.exposurenotification.proto;

public final class KeyFile {
  private KeyFile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_android_apps_exposurenotification_debug_TemporaryExposureKeyExport_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_google_android_apps_exposurenotification_debug_TemporaryExposureKeyExport_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_android_apps_exposurenotification_debug_SignatureInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_google_android_apps_exposurenotification_debug_SignatureInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_android_apps_exposurenotification_debug_TemporaryExposureKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_google_android_apps_exposurenotification_debug_TemporaryExposureKey_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_android_apps_exposurenotification_debug_TEKSignatureList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_google_android_apps_exposurenotification_debug_TEKSignatureList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_android_apps_exposurenotification_debug_TEKSignature_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_google_android_apps_exposurenotification_debug_TEKSignature_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016key_file.proto\0222com.google.android.app" +
      "s.exposurenotification.debug\"\267\002\n\032Tempora" +
      "ryExposureKeyExport\022\027\n\017start_timestamp\030\001" +
      " \001(\006\022\025\n\rend_timestamp\030\002 \001(\006\022\016\n\006region\030\003 " +
      "\001(\t\022\021\n\tbatch_num\030\004 \001(\005\022\022\n\nbatch_size\030\005 \001" +
      "(\005\022Z\n\017signature_infos\030\006 \003(\0132A.com.google" +
      ".android.apps.exposurenotification.debug" +
      ".SignatureInfo\022V\n\004keys\030\007 \003(\0132H.com.googl" +
      "e.android.apps.exposurenotification.debu" +
      "g.TemporaryExposureKey\"\227\001\n\rSignatureInfo" +
      "\022 \n\030verification_key_version\030\003 \001(\t\022\033\n\023ve" +
      "rification_key_id\030\004 \001(\t\022\033\n\023signature_alg" +
      "orithm\030\005 \001(\tJ\004\010\001\020\002J\004\010\002\020\003R\rapp_bundle_idR" +
      "\017android_package\"\215\001\n\024TemporaryExposureKe" +
      "y\022\020\n\010key_data\030\001 \001(\014\022\037\n\027transmission_risk" +
      "_level\030\002 \001(\005\022%\n\035rolling_start_interval_n" +
      "umber\030\003 \001(\005\022\033\n\016rolling_period\030\004 \001(\005:\003144" +
      "\"h\n\020TEKSignatureList\022T\n\nsignatures\030\001 \003(\013" +
      "2@.com.google.android.apps.exposurenotif" +
      "ication.debug.TEKSignature\"\243\001\n\014TEKSignat" +
      "ure\022Y\n\016signature_info\030\001 \001(\0132A.com.google" +
      ".android.apps.exposurenotification.debug" +
      ".SignatureInfo\022\021\n\tbatch_num\030\002 \001(\005\022\022\n\nbat" +
      "ch_size\030\003 \001(\005\022\021\n\tsignature\030\004 \001(\014B6\n2com." +
      "google.android.apps.exposurenotification" +
      ".protoP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_google_android_apps_exposurenotification_debug_TemporaryExposureKeyExport_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_google_android_apps_exposurenotification_debug_TemporaryExposureKeyExport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_google_android_apps_exposurenotification_debug_TemporaryExposureKeyExport_descriptor,
        new java.lang.String[] { "StartTimestamp", "EndTimestamp", "Region", "BatchNum", "BatchSize", "SignatureInfos", "Keys", });
    internal_static_com_google_android_apps_exposurenotification_debug_SignatureInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_google_android_apps_exposurenotification_debug_SignatureInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_google_android_apps_exposurenotification_debug_SignatureInfo_descriptor,
        new java.lang.String[] { "VerificationKeyVersion", "VerificationKeyId", "SignatureAlgorithm", });
    internal_static_com_google_android_apps_exposurenotification_debug_TemporaryExposureKey_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_google_android_apps_exposurenotification_debug_TemporaryExposureKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_google_android_apps_exposurenotification_debug_TemporaryExposureKey_descriptor,
        new java.lang.String[] { "KeyData", "TransmissionRiskLevel", "RollingStartIntervalNumber", "RollingPeriod", });
    internal_static_com_google_android_apps_exposurenotification_debug_TEKSignatureList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_google_android_apps_exposurenotification_debug_TEKSignatureList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_google_android_apps_exposurenotification_debug_TEKSignatureList_descriptor,
        new java.lang.String[] { "Signatures", });
    internal_static_com_google_android_apps_exposurenotification_debug_TEKSignature_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_google_android_apps_exposurenotification_debug_TEKSignature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_google_android_apps_exposurenotification_debug_TEKSignature_descriptor,
        new java.lang.String[] { "SignatureInfo", "BatchNum", "BatchSize", "Signature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
