// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: key_file.proto

package com.google.android.apps.exposurenotification.proto;

public interface SignatureInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.google.android.apps.exposurenotification.debug.SignatureInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Key version for rollovers
   * Must be in character class [a-zA-Z0-9_]. E.g., 'v1'
   * </pre>
   *
   * <code>optional string verification_key_version = 3;</code>
   * @return Whether the verificationKeyVersion field is set.
   */
  boolean hasVerificationKeyVersion();
  /**
   * <pre>
   * Key version for rollovers
   * Must be in character class [a-zA-Z0-9_]. E.g., 'v1'
   * </pre>
   *
   * <code>optional string verification_key_version = 3;</code>
   * @return The verificationKeyVersion.
   */
  java.lang.String getVerificationKeyVersion();
  /**
   * <pre>
   * Key version for rollovers
   * Must be in character class [a-zA-Z0-9_]. E.g., 'v1'
   * </pre>
   *
   * <code>optional string verification_key_version = 3;</code>
   * @return The bytes for verificationKeyVersion.
   */
  com.google.protobuf.ByteString
      getVerificationKeyVersionBytes();

  /**
   * <pre>
   * Additional identifying information
   * Must be in character class [a-zA-Z0-9_]
   * For cross-compatibility with Apple, use MCC (https://en.wikipedia.org/wiki/Mobile_country_code)
   * </pre>
   *
   * <code>optional string verification_key_id = 4;</code>
   * @return Whether the verificationKeyId field is set.
   */
  boolean hasVerificationKeyId();
  /**
   * <pre>
   * Additional identifying information
   * Must be in character class [a-zA-Z0-9_]
   * For cross-compatibility with Apple, use MCC (https://en.wikipedia.org/wiki/Mobile_country_code)
   * </pre>
   *
   * <code>optional string verification_key_id = 4;</code>
   * @return The verificationKeyId.
   */
  java.lang.String getVerificationKeyId();
  /**
   * <pre>
   * Additional identifying information
   * Must be in character class [a-zA-Z0-9_]
   * For cross-compatibility with Apple, use MCC (https://en.wikipedia.org/wiki/Mobile_country_code)
   * </pre>
   *
   * <code>optional string verification_key_id = 4;</code>
   * @return The bytes for verificationKeyId.
   */
  com.google.protobuf.ByteString
      getVerificationKeyIdBytes();

  /**
   * <pre>
   * ASN.1 OID for Algorithm Identifier.
   * For cross-compatibility with Apple, use '1.2.840.10045.4.3.2'
   * </pre>
   *
   * <code>optional string signature_algorithm = 5;</code>
   * @return Whether the signatureAlgorithm field is set.
   */
  boolean hasSignatureAlgorithm();
  /**
   * <pre>
   * ASN.1 OID for Algorithm Identifier.
   * For cross-compatibility with Apple, use '1.2.840.10045.4.3.2'
   * </pre>
   *
   * <code>optional string signature_algorithm = 5;</code>
   * @return The signatureAlgorithm.
   */
  java.lang.String getSignatureAlgorithm();
  /**
   * <pre>
   * ASN.1 OID for Algorithm Identifier.
   * For cross-compatibility with Apple, use '1.2.840.10045.4.3.2'
   * </pre>
   *
   * <code>optional string signature_algorithm = 5;</code>
   * @return The bytes for signatureAlgorithm.
   */
  com.google.protobuf.ByteString
      getSignatureAlgorithmBytes();
}
