// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: key_file.proto

package com.google.android.apps.exposurenotification.proto;

public interface TEKSignatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.google.android.apps.exposurenotification.debug.TEKSignature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Info about the signing key, version, algorithm, etc
   * </pre>
   *
   * <code>optional .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_info = 1;</code>
   * @return Whether the signatureInfo field is set.
   */
  boolean hasSignatureInfo();
  /**
   * <pre>
   * Info about the signing key, version, algorithm, etc
   * </pre>
   *
   * <code>optional .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_info = 1;</code>
   * @return The signatureInfo.
   */
  com.google.android.apps.exposurenotification.proto.SignatureInfo getSignatureInfo();
  /**
   * <pre>
   * Info about the signing key, version, algorithm, etc
   * </pre>
   *
   * <code>optional .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_info = 1;</code>
   */
  com.google.android.apps.exposurenotification.proto.SignatureInfoOrBuilder getSignatureInfoOrBuilder();

  /**
   * <pre>
   * E.g., Batch 2 of 10
   * </pre>
   *
   * <code>optional int32 batch_num = 2;</code>
   * @return Whether the batchNum field is set.
   */
  boolean hasBatchNum();
  /**
   * <pre>
   * E.g., Batch 2 of 10
   * </pre>
   *
   * <code>optional int32 batch_num = 2;</code>
   * @return The batchNum.
   */
  int getBatchNum();

  /**
   * <code>optional int32 batch_size = 3;</code>
   * @return Whether the batchSize field is set.
   */
  boolean hasBatchSize();
  /**
   * <code>optional int32 batch_size = 3;</code>
   * @return The batchSize.
   */
  int getBatchSize();

  /**
   * <pre>
   * Signature in X9.62 format (ASN.1 SEQUENCE of two INTEGER fields)
   * </pre>
   *
   * <code>optional bytes signature = 4;</code>
   * @return Whether the signature field is set.
   */
  boolean hasSignature();
  /**
   * <pre>
   * Signature in X9.62 format (ASN.1 SEQUENCE of two INTEGER fields)
   * </pre>
   *
   * <code>optional bytes signature = 4;</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();
}
