// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: key_file.proto

package com.google.android.apps.exposurenotification.proto;

/**
 * Protobuf type {@code com.google.android.apps.exposurenotification.debug.TEKSignature}
 */
public  final class TEKSignature extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.google.android.apps.exposurenotification.debug.TEKSignature)
    TEKSignatureOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TEKSignature.newBuilder() to construct.
  private TEKSignature(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TEKSignature() {
    signature_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TEKSignature();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TEKSignature(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.android.apps.exposurenotification.proto.SignatureInfo.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) != 0)) {
              subBuilder = signatureInfo_.toBuilder();
            }
            signatureInfo_ = input.readMessage(com.google.android.apps.exposurenotification.proto.SignatureInfo.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(signatureInfo_);
              signatureInfo_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            batchNum_ = input.readInt32();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            batchSize_ = input.readInt32();
            break;
          }
          case 34: {
            bitField0_ |= 0x00000008;
            signature_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.android.apps.exposurenotification.proto.KeyFile.internal_static_com_google_android_apps_exposurenotification_debug_TEKSignature_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.android.apps.exposurenotification.proto.KeyFile.internal_static_com_google_android_apps_exposurenotification_debug_TEKSignature_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.android.apps.exposurenotification.proto.TEKSignature.class, com.google.android.apps.exposurenotification.proto.TEKSignature.Builder.class);
  }

  private int bitField0_;
  public static final int SIGNATURE_INFO_FIELD_NUMBER = 1;
  private com.google.android.apps.exposurenotification.proto.SignatureInfo signatureInfo_;
  /**
   * <pre>
   * Info about the signing key, version, algorithm, etc
   * </pre>
   *
   * <code>optional .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_info = 1;</code>
   * @return Whether the signatureInfo field is set.
   */
  public boolean hasSignatureInfo() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Info about the signing key, version, algorithm, etc
   * </pre>
   *
   * <code>optional .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_info = 1;</code>
   * @return The signatureInfo.
   */
  public com.google.android.apps.exposurenotification.proto.SignatureInfo getSignatureInfo() {
    return signatureInfo_ == null ? com.google.android.apps.exposurenotification.proto.SignatureInfo.getDefaultInstance() : signatureInfo_;
  }
  /**
   * <pre>
   * Info about the signing key, version, algorithm, etc
   * </pre>
   *
   * <code>optional .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_info = 1;</code>
   */
  public com.google.android.apps.exposurenotification.proto.SignatureInfoOrBuilder getSignatureInfoOrBuilder() {
    return signatureInfo_ == null ? com.google.android.apps.exposurenotification.proto.SignatureInfo.getDefaultInstance() : signatureInfo_;
  }

  public static final int BATCH_NUM_FIELD_NUMBER = 2;
  private int batchNum_;
  /**
   * <pre>
   * E.g., Batch 2 of 10
   * </pre>
   *
   * <code>optional int32 batch_num = 2;</code>
   * @return Whether the batchNum field is set.
   */
  public boolean hasBatchNum() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * E.g., Batch 2 of 10
   * </pre>
   *
   * <code>optional int32 batch_num = 2;</code>
   * @return The batchNum.
   */
  public int getBatchNum() {
    return batchNum_;
  }

  public static final int BATCH_SIZE_FIELD_NUMBER = 3;
  private int batchSize_;
  /**
   * <code>optional int32 batch_size = 3;</code>
   * @return Whether the batchSize field is set.
   */
  public boolean hasBatchSize() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int32 batch_size = 3;</code>
   * @return The batchSize.
   */
  public int getBatchSize() {
    return batchSize_;
  }

  public static final int SIGNATURE_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString signature_;
  /**
   * <pre>
   * Signature in X9.62 format (ASN.1 SEQUENCE of two INTEGER fields)
   * </pre>
   *
   * <code>optional bytes signature = 4;</code>
   * @return Whether the signature field is set.
   */
  public boolean hasSignature() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * Signature in X9.62 format (ASN.1 SEQUENCE of two INTEGER fields)
   * </pre>
   *
   * <code>optional bytes signature = 4;</code>
   * @return The signature.
   */
  public com.google.protobuf.ByteString getSignature() {
    return signature_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getSignatureInfo());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, batchNum_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(3, batchSize_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeBytes(4, signature_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSignatureInfo());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, batchNum_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, batchSize_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, signature_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.android.apps.exposurenotification.proto.TEKSignature)) {
      return super.equals(obj);
    }
    com.google.android.apps.exposurenotification.proto.TEKSignature other = (com.google.android.apps.exposurenotification.proto.TEKSignature) obj;

    if (hasSignatureInfo() != other.hasSignatureInfo()) return false;
    if (hasSignatureInfo()) {
      if (!getSignatureInfo()
          .equals(other.getSignatureInfo())) return false;
    }
    if (hasBatchNum() != other.hasBatchNum()) return false;
    if (hasBatchNum()) {
      if (getBatchNum()
          != other.getBatchNum()) return false;
    }
    if (hasBatchSize() != other.hasBatchSize()) return false;
    if (hasBatchSize()) {
      if (getBatchSize()
          != other.getBatchSize()) return false;
    }
    if (hasSignature() != other.hasSignature()) return false;
    if (hasSignature()) {
      if (!getSignature()
          .equals(other.getSignature())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSignatureInfo()) {
      hash = (37 * hash) + SIGNATURE_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getSignatureInfo().hashCode();
    }
    if (hasBatchNum()) {
      hash = (37 * hash) + BATCH_NUM_FIELD_NUMBER;
      hash = (53 * hash) + getBatchNum();
    }
    if (hasBatchSize()) {
      hash = (37 * hash) + BATCH_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getBatchSize();
    }
    if (hasSignature()) {
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.android.apps.exposurenotification.proto.TEKSignature parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.android.apps.exposurenotification.proto.TEKSignature parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.android.apps.exposurenotification.proto.TEKSignature parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.android.apps.exposurenotification.proto.TEKSignature parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.android.apps.exposurenotification.proto.TEKSignature parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.android.apps.exposurenotification.proto.TEKSignature parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.android.apps.exposurenotification.proto.TEKSignature parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.android.apps.exposurenotification.proto.TEKSignature parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.android.apps.exposurenotification.proto.TEKSignature parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.android.apps.exposurenotification.proto.TEKSignature parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.android.apps.exposurenotification.proto.TEKSignature parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.android.apps.exposurenotification.proto.TEKSignature parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.android.apps.exposurenotification.proto.TEKSignature prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.google.android.apps.exposurenotification.debug.TEKSignature}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.google.android.apps.exposurenotification.debug.TEKSignature)
      com.google.android.apps.exposurenotification.proto.TEKSignatureOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.android.apps.exposurenotification.proto.KeyFile.internal_static_com_google_android_apps_exposurenotification_debug_TEKSignature_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.android.apps.exposurenotification.proto.KeyFile.internal_static_com_google_android_apps_exposurenotification_debug_TEKSignature_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.android.apps.exposurenotification.proto.TEKSignature.class, com.google.android.apps.exposurenotification.proto.TEKSignature.Builder.class);
    }

    // Construct using com.google.android.apps.exposurenotification.proto.TEKSignature.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSignatureInfoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (signatureInfoBuilder_ == null) {
        signatureInfo_ = null;
      } else {
        signatureInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      batchNum_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      batchSize_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      signature_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.android.apps.exposurenotification.proto.KeyFile.internal_static_com_google_android_apps_exposurenotification_debug_TEKSignature_descriptor;
    }

    @java.lang.Override
    public com.google.android.apps.exposurenotification.proto.TEKSignature getDefaultInstanceForType() {
      return com.google.android.apps.exposurenotification.proto.TEKSignature.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.android.apps.exposurenotification.proto.TEKSignature build() {
      com.google.android.apps.exposurenotification.proto.TEKSignature result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.android.apps.exposurenotification.proto.TEKSignature buildPartial() {
      com.google.android.apps.exposurenotification.proto.TEKSignature result = new com.google.android.apps.exposurenotification.proto.TEKSignature(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (signatureInfoBuilder_ == null) {
          result.signatureInfo_ = signatureInfo_;
        } else {
          result.signatureInfo_ = signatureInfoBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.batchNum_ = batchNum_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.batchSize_ = batchSize_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.signature_ = signature_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.android.apps.exposurenotification.proto.TEKSignature) {
        return mergeFrom((com.google.android.apps.exposurenotification.proto.TEKSignature)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.android.apps.exposurenotification.proto.TEKSignature other) {
      if (other == com.google.android.apps.exposurenotification.proto.TEKSignature.getDefaultInstance()) return this;
      if (other.hasSignatureInfo()) {
        mergeSignatureInfo(other.getSignatureInfo());
      }
      if (other.hasBatchNum()) {
        setBatchNum(other.getBatchNum());
      }
      if (other.hasBatchSize()) {
        setBatchSize(other.getBatchSize());
      }
      if (other.hasSignature()) {
        setSignature(other.getSignature());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.android.apps.exposurenotification.proto.TEKSignature parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.android.apps.exposurenotification.proto.TEKSignature) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.android.apps.exposurenotification.proto.SignatureInfo signatureInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.android.apps.exposurenotification.proto.SignatureInfo, com.google.android.apps.exposurenotification.proto.SignatureInfo.Builder, com.google.android.apps.exposurenotification.proto.SignatureInfoOrBuilder> signatureInfoBuilder_;
    /**
     * <pre>
     * Info about the signing key, version, algorithm, etc
     * </pre>
     *
     * <code>optional .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_info = 1;</code>
     * @return Whether the signatureInfo field is set.
     */
    public boolean hasSignatureInfo() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Info about the signing key, version, algorithm, etc
     * </pre>
     *
     * <code>optional .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_info = 1;</code>
     * @return The signatureInfo.
     */
    public com.google.android.apps.exposurenotification.proto.SignatureInfo getSignatureInfo() {
      if (signatureInfoBuilder_ == null) {
        return signatureInfo_ == null ? com.google.android.apps.exposurenotification.proto.SignatureInfo.getDefaultInstance() : signatureInfo_;
      } else {
        return signatureInfoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Info about the signing key, version, algorithm, etc
     * </pre>
     *
     * <code>optional .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_info = 1;</code>
     */
    public Builder setSignatureInfo(com.google.android.apps.exposurenotification.proto.SignatureInfo value) {
      if (signatureInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        signatureInfo_ = value;
        onChanged();
      } else {
        signatureInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * Info about the signing key, version, algorithm, etc
     * </pre>
     *
     * <code>optional .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_info = 1;</code>
     */
    public Builder setSignatureInfo(
        com.google.android.apps.exposurenotification.proto.SignatureInfo.Builder builderForValue) {
      if (signatureInfoBuilder_ == null) {
        signatureInfo_ = builderForValue.build();
        onChanged();
      } else {
        signatureInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * Info about the signing key, version, algorithm, etc
     * </pre>
     *
     * <code>optional .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_info = 1;</code>
     */
    public Builder mergeSignatureInfo(com.google.android.apps.exposurenotification.proto.SignatureInfo value) {
      if (signatureInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            signatureInfo_ != null &&
            signatureInfo_ != com.google.android.apps.exposurenotification.proto.SignatureInfo.getDefaultInstance()) {
          signatureInfo_ =
            com.google.android.apps.exposurenotification.proto.SignatureInfo.newBuilder(signatureInfo_).mergeFrom(value).buildPartial();
        } else {
          signatureInfo_ = value;
        }
        onChanged();
      } else {
        signatureInfoBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * Info about the signing key, version, algorithm, etc
     * </pre>
     *
     * <code>optional .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_info = 1;</code>
     */
    public Builder clearSignatureInfo() {
      if (signatureInfoBuilder_ == null) {
        signatureInfo_ = null;
        onChanged();
      } else {
        signatureInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <pre>
     * Info about the signing key, version, algorithm, etc
     * </pre>
     *
     * <code>optional .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_info = 1;</code>
     */
    public com.google.android.apps.exposurenotification.proto.SignatureInfo.Builder getSignatureInfoBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getSignatureInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Info about the signing key, version, algorithm, etc
     * </pre>
     *
     * <code>optional .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_info = 1;</code>
     */
    public com.google.android.apps.exposurenotification.proto.SignatureInfoOrBuilder getSignatureInfoOrBuilder() {
      if (signatureInfoBuilder_ != null) {
        return signatureInfoBuilder_.getMessageOrBuilder();
      } else {
        return signatureInfo_ == null ?
            com.google.android.apps.exposurenotification.proto.SignatureInfo.getDefaultInstance() : signatureInfo_;
      }
    }
    /**
     * <pre>
     * Info about the signing key, version, algorithm, etc
     * </pre>
     *
     * <code>optional .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_info = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.android.apps.exposurenotification.proto.SignatureInfo, com.google.android.apps.exposurenotification.proto.SignatureInfo.Builder, com.google.android.apps.exposurenotification.proto.SignatureInfoOrBuilder> 
        getSignatureInfoFieldBuilder() {
      if (signatureInfoBuilder_ == null) {
        signatureInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.android.apps.exposurenotification.proto.SignatureInfo, com.google.android.apps.exposurenotification.proto.SignatureInfo.Builder, com.google.android.apps.exposurenotification.proto.SignatureInfoOrBuilder>(
                getSignatureInfo(),
                getParentForChildren(),
                isClean());
        signatureInfo_ = null;
      }
      return signatureInfoBuilder_;
    }

    private int batchNum_ ;
    /**
     * <pre>
     * E.g., Batch 2 of 10
     * </pre>
     *
     * <code>optional int32 batch_num = 2;</code>
     * @return Whether the batchNum field is set.
     */
    public boolean hasBatchNum() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * E.g., Batch 2 of 10
     * </pre>
     *
     * <code>optional int32 batch_num = 2;</code>
     * @return The batchNum.
     */
    public int getBatchNum() {
      return batchNum_;
    }
    /**
     * <pre>
     * E.g., Batch 2 of 10
     * </pre>
     *
     * <code>optional int32 batch_num = 2;</code>
     * @param value The batchNum to set.
     * @return This builder for chaining.
     */
    public Builder setBatchNum(int value) {
      bitField0_ |= 0x00000002;
      batchNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * E.g., Batch 2 of 10
     * </pre>
     *
     * <code>optional int32 batch_num = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBatchNum() {
      bitField0_ = (bitField0_ & ~0x00000002);
      batchNum_ = 0;
      onChanged();
      return this;
    }

    private int batchSize_ ;
    /**
     * <code>optional int32 batch_size = 3;</code>
     * @return Whether the batchSize field is set.
     */
    public boolean hasBatchSize() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 batch_size = 3;</code>
     * @return The batchSize.
     */
    public int getBatchSize() {
      return batchSize_;
    }
    /**
     * <code>optional int32 batch_size = 3;</code>
     * @param value The batchSize to set.
     * @return This builder for chaining.
     */
    public Builder setBatchSize(int value) {
      bitField0_ |= 0x00000004;
      batchSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 batch_size = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBatchSize() {
      bitField0_ = (bitField0_ & ~0x00000004);
      batchSize_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Signature in X9.62 format (ASN.1 SEQUENCE of two INTEGER fields)
     * </pre>
     *
     * <code>optional bytes signature = 4;</code>
     * @return Whether the signature field is set.
     */
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Signature in X9.62 format (ASN.1 SEQUENCE of two INTEGER fields)
     * </pre>
     *
     * <code>optional bytes signature = 4;</code>
     * @return The signature.
     */
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }
    /**
     * <pre>
     * Signature in X9.62 format (ASN.1 SEQUENCE of two INTEGER fields)
     * </pre>
     *
     * <code>optional bytes signature = 4;</code>
     * @param value The signature to set.
     * @return This builder for chaining.
     */
    public Builder setSignature(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      signature_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Signature in X9.62 format (ASN.1 SEQUENCE of two INTEGER fields)
     * </pre>
     *
     * <code>optional bytes signature = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignature() {
      bitField0_ = (bitField0_ & ~0x00000008);
      signature_ = getDefaultInstance().getSignature();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.google.android.apps.exposurenotification.debug.TEKSignature)
  }

  // @@protoc_insertion_point(class_scope:com.google.android.apps.exposurenotification.debug.TEKSignature)
  private static final com.google.android.apps.exposurenotification.proto.TEKSignature DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.android.apps.exposurenotification.proto.TEKSignature();
  }

  public static com.google.android.apps.exposurenotification.proto.TEKSignature getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<TEKSignature>
      PARSER = new com.google.protobuf.AbstractParser<TEKSignature>() {
    @java.lang.Override
    public TEKSignature parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TEKSignature(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TEKSignature> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TEKSignature> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.android.apps.exposurenotification.proto.TEKSignature getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

