// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: key_file.proto

package com.google.android.apps.exposurenotification.proto;

public interface TEKSignatureListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.google.android.apps.exposurenotification.debug.TEKSignatureList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.google.android.apps.exposurenotification.debug.TEKSignature signatures = 1;</code>
   */
  java.util.List<com.google.android.apps.exposurenotification.proto.TEKSignature> 
      getSignaturesList();
  /**
   * <code>repeated .com.google.android.apps.exposurenotification.debug.TEKSignature signatures = 1;</code>
   */
  com.google.android.apps.exposurenotification.proto.TEKSignature getSignatures(int index);
  /**
   * <code>repeated .com.google.android.apps.exposurenotification.debug.TEKSignature signatures = 1;</code>
   */
  int getSignaturesCount();
  /**
   * <code>repeated .com.google.android.apps.exposurenotification.debug.TEKSignature signatures = 1;</code>
   */
  java.util.List<? extends com.google.android.apps.exposurenotification.proto.TEKSignatureOrBuilder> 
      getSignaturesOrBuilderList();
  /**
   * <code>repeated .com.google.android.apps.exposurenotification.debug.TEKSignature signatures = 1;</code>
   */
  com.google.android.apps.exposurenotification.proto.TEKSignatureOrBuilder getSignaturesOrBuilder(
      int index);
}
