// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: key_file.proto

package com.google.android.apps.exposurenotification.proto;

public interface TemporaryExposureKeyExportOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.google.android.apps.exposurenotification.debug.TemporaryExposureKeyExport)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Time window of keys in this file based on arrival to server, in UTC
   * seconds
   * </pre>
   *
   * <code>optional fixed64 start_timestamp = 1;</code>
   * @return Whether the startTimestamp field is set.
   */
  boolean hasStartTimestamp();
  /**
   * <pre>
   * Time window of keys in this file based on arrival to server, in UTC
   * seconds
   * </pre>
   *
   * <code>optional fixed64 start_timestamp = 1;</code>
   * @return The startTimestamp.
   */
  long getStartTimestamp();

  /**
   * <code>optional fixed64 end_timestamp = 2;</code>
   * @return Whether the endTimestamp field is set.
   */
  boolean hasEndTimestamp();
  /**
   * <code>optional fixed64 end_timestamp = 2;</code>
   * @return The endTimestamp.
   */
  long getEndTimestamp();

  /**
   * <pre>
   * Region for which these keys came from (e.g., country)
   * </pre>
   *
   * <code>optional string region = 3;</code>
   * @return Whether the region field is set.
   */
  boolean hasRegion();
  /**
   * <pre>
   * Region for which these keys came from (e.g., country)
   * </pre>
   *
   * <code>optional string region = 3;</code>
   * @return The region.
   */
  java.lang.String getRegion();
  /**
   * <pre>
   * Region for which these keys came from (e.g., country)
   * </pre>
   *
   * <code>optional string region = 3;</code>
   * @return The bytes for region.
   */
  com.google.protobuf.ByteString
      getRegionBytes();

  /**
   * <pre>
   * E.g., Batch 2 of 10. Ordinal, 1-based numbering.
   * Note: Not yet supported on iOS. Use values of 1 for both.
   * </pre>
   *
   * <code>optional int32 batch_num = 4;</code>
   * @return Whether the batchNum field is set.
   */
  boolean hasBatchNum();
  /**
   * <pre>
   * E.g., Batch 2 of 10. Ordinal, 1-based numbering.
   * Note: Not yet supported on iOS. Use values of 1 for both.
   * </pre>
   *
   * <code>optional int32 batch_num = 4;</code>
   * @return The batchNum.
   */
  int getBatchNum();

  /**
   * <code>optional int32 batch_size = 5;</code>
   * @return Whether the batchSize field is set.
   */
  boolean hasBatchSize();
  /**
   * <code>optional int32 batch_size = 5;</code>
   * @return The batchSize.
   */
  int getBatchSize();

  /**
   * <pre>
   * Information about signatures
   * </pre>
   *
   * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
   */
  java.util.List<com.google.android.apps.exposurenotification.proto.SignatureInfo> 
      getSignatureInfosList();
  /**
   * <pre>
   * Information about signatures
   * </pre>
   *
   * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
   */
  com.google.android.apps.exposurenotification.proto.SignatureInfo getSignatureInfos(int index);
  /**
   * <pre>
   * Information about signatures
   * </pre>
   *
   * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
   */
  int getSignatureInfosCount();
  /**
   * <pre>
   * Information about signatures
   * </pre>
   *
   * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
   */
  java.util.List<? extends com.google.android.apps.exposurenotification.proto.SignatureInfoOrBuilder> 
      getSignatureInfosOrBuilderList();
  /**
   * <pre>
   * Information about signatures
   * </pre>
   *
   * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
   */
  com.google.android.apps.exposurenotification.proto.SignatureInfoOrBuilder getSignatureInfosOrBuilder(
      int index);

  /**
   * <pre>
   * The TemporaryExposureKeys themselves
   * </pre>
   *
   * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
   */
  java.util.List<com.google.android.apps.exposurenotification.proto.TemporaryExposureKey> 
      getKeysList();
  /**
   * <pre>
   * The TemporaryExposureKeys themselves
   * </pre>
   *
   * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
   */
  com.google.android.apps.exposurenotification.proto.TemporaryExposureKey getKeys(int index);
  /**
   * <pre>
   * The TemporaryExposureKeys themselves
   * </pre>
   *
   * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
   */
  int getKeysCount();
  /**
   * <pre>
   * The TemporaryExposureKeys themselves
   * </pre>
   *
   * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
   */
  java.util.List<? extends com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyOrBuilder> 
      getKeysOrBuilderList();
  /**
   * <pre>
   * The TemporaryExposureKeys themselves
   * </pre>
   *
   * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
   */
  com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyOrBuilder getKeysOrBuilder(
      int index);
}
