// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: key_file.proto

package com.google.android.apps.exposurenotification.proto;

/**
 * Protobuf type {@code com.google.android.apps.exposurenotification.debug.TemporaryExposureKey}
 */
public  final class TemporaryExposureKey extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.google.android.apps.exposurenotification.debug.TemporaryExposureKey)
    TemporaryExposureKeyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TemporaryExposureKey.newBuilder() to construct.
  private TemporaryExposureKey(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TemporaryExposureKey() {
    keyData_ = com.google.protobuf.ByteString.EMPTY;
    rollingPeriod_ = 144;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TemporaryExposureKey();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TemporaryExposureKey(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            bitField0_ |= 0x00000001;
            keyData_ = input.readBytes();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            transmissionRiskLevel_ = input.readInt32();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            rollingStartIntervalNumber_ = input.readInt32();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            rollingPeriod_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.android.apps.exposurenotification.proto.KeyFile.internal_static_com_google_android_apps_exposurenotification_debug_TemporaryExposureKey_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.android.apps.exposurenotification.proto.KeyFile.internal_static_com_google_android_apps_exposurenotification_debug_TemporaryExposureKey_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.android.apps.exposurenotification.proto.TemporaryExposureKey.class, com.google.android.apps.exposurenotification.proto.TemporaryExposureKey.Builder.class);
  }

  private int bitField0_;
  public static final int KEY_DATA_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString keyData_;
  /**
   * <pre>
   * Key of infected user
   * </pre>
   *
   * <code>optional bytes key_data = 1;</code>
   * @return Whether the keyData field is set.
   */
  public boolean hasKeyData() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Key of infected user
   * </pre>
   *
   * <code>optional bytes key_data = 1;</code>
   * @return The keyData.
   */
  public com.google.protobuf.ByteString getKeyData() {
    return keyData_;
  }

  public static final int TRANSMISSION_RISK_LEVEL_FIELD_NUMBER = 2;
  private int transmissionRiskLevel_;
  /**
   * <pre>
   * Varying risks associated with exposure depending on type of verification
   * </pre>
   *
   * <code>optional int32 transmission_risk_level = 2;</code>
   * @return Whether the transmissionRiskLevel field is set.
   */
  public boolean hasTransmissionRiskLevel() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Varying risks associated with exposure depending on type of verification
   * </pre>
   *
   * <code>optional int32 transmission_risk_level = 2;</code>
   * @return The transmissionRiskLevel.
   */
  public int getTransmissionRiskLevel() {
    return transmissionRiskLevel_;
  }

  public static final int ROLLING_START_INTERVAL_NUMBER_FIELD_NUMBER = 3;
  private int rollingStartIntervalNumber_;
  /**
   * <pre>
   * The interval number since epoch for which a key starts
   * </pre>
   *
   * <code>optional int32 rolling_start_interval_number = 3;</code>
   * @return Whether the rollingStartIntervalNumber field is set.
   */
  public boolean hasRollingStartIntervalNumber() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * The interval number since epoch for which a key starts
   * </pre>
   *
   * <code>optional int32 rolling_start_interval_number = 3;</code>
   * @return The rollingStartIntervalNumber.
   */
  public int getRollingStartIntervalNumber() {
    return rollingStartIntervalNumber_;
  }

  public static final int ROLLING_PERIOD_FIELD_NUMBER = 4;
  private int rollingPeriod_;
  /**
   * <pre>
   * Increments of 10 minutes describing how long a key is valid
   * </pre>
   *
   * <code>optional int32 rolling_period = 4 [default = 144];</code>
   * @return Whether the rollingPeriod field is set.
   */
  public boolean hasRollingPeriod() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * Increments of 10 minutes describing how long a key is valid
   * </pre>
   *
   * <code>optional int32 rolling_period = 4 [default = 144];</code>
   * @return The rollingPeriod.
   */
  public int getRollingPeriod() {
    return rollingPeriod_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBytes(1, keyData_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, transmissionRiskLevel_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(3, rollingStartIntervalNumber_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt32(4, rollingPeriod_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, keyData_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, transmissionRiskLevel_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, rollingStartIntervalNumber_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, rollingPeriod_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.android.apps.exposurenotification.proto.TemporaryExposureKey)) {
      return super.equals(obj);
    }
    com.google.android.apps.exposurenotification.proto.TemporaryExposureKey other = (com.google.android.apps.exposurenotification.proto.TemporaryExposureKey) obj;

    if (hasKeyData() != other.hasKeyData()) return false;
    if (hasKeyData()) {
      if (!getKeyData()
          .equals(other.getKeyData())) return false;
    }
    if (hasTransmissionRiskLevel() != other.hasTransmissionRiskLevel()) return false;
    if (hasTransmissionRiskLevel()) {
      if (getTransmissionRiskLevel()
          != other.getTransmissionRiskLevel()) return false;
    }
    if (hasRollingStartIntervalNumber() != other.hasRollingStartIntervalNumber()) return false;
    if (hasRollingStartIntervalNumber()) {
      if (getRollingStartIntervalNumber()
          != other.getRollingStartIntervalNumber()) return false;
    }
    if (hasRollingPeriod() != other.hasRollingPeriod()) return false;
    if (hasRollingPeriod()) {
      if (getRollingPeriod()
          != other.getRollingPeriod()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasKeyData()) {
      hash = (37 * hash) + KEY_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getKeyData().hashCode();
    }
    if (hasTransmissionRiskLevel()) {
      hash = (37 * hash) + TRANSMISSION_RISK_LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getTransmissionRiskLevel();
    }
    if (hasRollingStartIntervalNumber()) {
      hash = (37 * hash) + ROLLING_START_INTERVAL_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getRollingStartIntervalNumber();
    }
    if (hasRollingPeriod()) {
      hash = (37 * hash) + ROLLING_PERIOD_FIELD_NUMBER;
      hash = (53 * hash) + getRollingPeriod();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.android.apps.exposurenotification.proto.TemporaryExposureKey parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.android.apps.exposurenotification.proto.TemporaryExposureKey parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.android.apps.exposurenotification.proto.TemporaryExposureKey parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.android.apps.exposurenotification.proto.TemporaryExposureKey parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.android.apps.exposurenotification.proto.TemporaryExposureKey parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.android.apps.exposurenotification.proto.TemporaryExposureKey parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.android.apps.exposurenotification.proto.TemporaryExposureKey parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.android.apps.exposurenotification.proto.TemporaryExposureKey parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.android.apps.exposurenotification.proto.TemporaryExposureKey parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.android.apps.exposurenotification.proto.TemporaryExposureKey parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.android.apps.exposurenotification.proto.TemporaryExposureKey parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.android.apps.exposurenotification.proto.TemporaryExposureKey parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.android.apps.exposurenotification.proto.TemporaryExposureKey prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.google.android.apps.exposurenotification.debug.TemporaryExposureKey}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.google.android.apps.exposurenotification.debug.TemporaryExposureKey)
      com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.android.apps.exposurenotification.proto.KeyFile.internal_static_com_google_android_apps_exposurenotification_debug_TemporaryExposureKey_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.android.apps.exposurenotification.proto.KeyFile.internal_static_com_google_android_apps_exposurenotification_debug_TemporaryExposureKey_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.android.apps.exposurenotification.proto.TemporaryExposureKey.class, com.google.android.apps.exposurenotification.proto.TemporaryExposureKey.Builder.class);
    }

    // Construct using com.google.android.apps.exposurenotification.proto.TemporaryExposureKey.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      keyData_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      transmissionRiskLevel_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      rollingStartIntervalNumber_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      rollingPeriod_ = 144;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.android.apps.exposurenotification.proto.KeyFile.internal_static_com_google_android_apps_exposurenotification_debug_TemporaryExposureKey_descriptor;
    }

    @java.lang.Override
    public com.google.android.apps.exposurenotification.proto.TemporaryExposureKey getDefaultInstanceForType() {
      return com.google.android.apps.exposurenotification.proto.TemporaryExposureKey.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.android.apps.exposurenotification.proto.TemporaryExposureKey build() {
      com.google.android.apps.exposurenotification.proto.TemporaryExposureKey result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.android.apps.exposurenotification.proto.TemporaryExposureKey buildPartial() {
      com.google.android.apps.exposurenotification.proto.TemporaryExposureKey result = new com.google.android.apps.exposurenotification.proto.TemporaryExposureKey(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.keyData_ = keyData_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.transmissionRiskLevel_ = transmissionRiskLevel_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.rollingStartIntervalNumber_ = rollingStartIntervalNumber_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.rollingPeriod_ = rollingPeriod_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.android.apps.exposurenotification.proto.TemporaryExposureKey) {
        return mergeFrom((com.google.android.apps.exposurenotification.proto.TemporaryExposureKey)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.android.apps.exposurenotification.proto.TemporaryExposureKey other) {
      if (other == com.google.android.apps.exposurenotification.proto.TemporaryExposureKey.getDefaultInstance()) return this;
      if (other.hasKeyData()) {
        setKeyData(other.getKeyData());
      }
      if (other.hasTransmissionRiskLevel()) {
        setTransmissionRiskLevel(other.getTransmissionRiskLevel());
      }
      if (other.hasRollingStartIntervalNumber()) {
        setRollingStartIntervalNumber(other.getRollingStartIntervalNumber());
      }
      if (other.hasRollingPeriod()) {
        setRollingPeriod(other.getRollingPeriod());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.android.apps.exposurenotification.proto.TemporaryExposureKey parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.android.apps.exposurenotification.proto.TemporaryExposureKey) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString keyData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Key of infected user
     * </pre>
     *
     * <code>optional bytes key_data = 1;</code>
     * @return Whether the keyData field is set.
     */
    public boolean hasKeyData() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Key of infected user
     * </pre>
     *
     * <code>optional bytes key_data = 1;</code>
     * @return The keyData.
     */
    public com.google.protobuf.ByteString getKeyData() {
      return keyData_;
    }
    /**
     * <pre>
     * Key of infected user
     * </pre>
     *
     * <code>optional bytes key_data = 1;</code>
     * @param value The keyData to set.
     * @return This builder for chaining.
     */
    public Builder setKeyData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      keyData_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Key of infected user
     * </pre>
     *
     * <code>optional bytes key_data = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearKeyData() {
      bitField0_ = (bitField0_ & ~0x00000001);
      keyData_ = getDefaultInstance().getKeyData();
      onChanged();
      return this;
    }

    private int transmissionRiskLevel_ ;
    /**
     * <pre>
     * Varying risks associated with exposure depending on type of verification
     * </pre>
     *
     * <code>optional int32 transmission_risk_level = 2;</code>
     * @return Whether the transmissionRiskLevel field is set.
     */
    public boolean hasTransmissionRiskLevel() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Varying risks associated with exposure depending on type of verification
     * </pre>
     *
     * <code>optional int32 transmission_risk_level = 2;</code>
     * @return The transmissionRiskLevel.
     */
    public int getTransmissionRiskLevel() {
      return transmissionRiskLevel_;
    }
    /**
     * <pre>
     * Varying risks associated with exposure depending on type of verification
     * </pre>
     *
     * <code>optional int32 transmission_risk_level = 2;</code>
     * @param value The transmissionRiskLevel to set.
     * @return This builder for chaining.
     */
    public Builder setTransmissionRiskLevel(int value) {
      bitField0_ |= 0x00000002;
      transmissionRiskLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Varying risks associated with exposure depending on type of verification
     * </pre>
     *
     * <code>optional int32 transmission_risk_level = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransmissionRiskLevel() {
      bitField0_ = (bitField0_ & ~0x00000002);
      transmissionRiskLevel_ = 0;
      onChanged();
      return this;
    }

    private int rollingStartIntervalNumber_ ;
    /**
     * <pre>
     * The interval number since epoch for which a key starts
     * </pre>
     *
     * <code>optional int32 rolling_start_interval_number = 3;</code>
     * @return Whether the rollingStartIntervalNumber field is set.
     */
    public boolean hasRollingStartIntervalNumber() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * The interval number since epoch for which a key starts
     * </pre>
     *
     * <code>optional int32 rolling_start_interval_number = 3;</code>
     * @return The rollingStartIntervalNumber.
     */
    public int getRollingStartIntervalNumber() {
      return rollingStartIntervalNumber_;
    }
    /**
     * <pre>
     * The interval number since epoch for which a key starts
     * </pre>
     *
     * <code>optional int32 rolling_start_interval_number = 3;</code>
     * @param value The rollingStartIntervalNumber to set.
     * @return This builder for chaining.
     */
    public Builder setRollingStartIntervalNumber(int value) {
      bitField0_ |= 0x00000004;
      rollingStartIntervalNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The interval number since epoch for which a key starts
     * </pre>
     *
     * <code>optional int32 rolling_start_interval_number = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRollingStartIntervalNumber() {
      bitField0_ = (bitField0_ & ~0x00000004);
      rollingStartIntervalNumber_ = 0;
      onChanged();
      return this;
    }

    private int rollingPeriod_ = 144;
    /**
     * <pre>
     * Increments of 10 minutes describing how long a key is valid
     * </pre>
     *
     * <code>optional int32 rolling_period = 4 [default = 144];</code>
     * @return Whether the rollingPeriod field is set.
     */
    public boolean hasRollingPeriod() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Increments of 10 minutes describing how long a key is valid
     * </pre>
     *
     * <code>optional int32 rolling_period = 4 [default = 144];</code>
     * @return The rollingPeriod.
     */
    public int getRollingPeriod() {
      return rollingPeriod_;
    }
    /**
     * <pre>
     * Increments of 10 minutes describing how long a key is valid
     * </pre>
     *
     * <code>optional int32 rolling_period = 4 [default = 144];</code>
     * @param value The rollingPeriod to set.
     * @return This builder for chaining.
     */
    public Builder setRollingPeriod(int value) {
      bitField0_ |= 0x00000008;
      rollingPeriod_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Increments of 10 minutes describing how long a key is valid
     * </pre>
     *
     * <code>optional int32 rolling_period = 4 [default = 144];</code>
     * @return This builder for chaining.
     */
    public Builder clearRollingPeriod() {
      bitField0_ = (bitField0_ & ~0x00000008);
      rollingPeriod_ = 144;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.google.android.apps.exposurenotification.debug.TemporaryExposureKey)
  }

  // @@protoc_insertion_point(class_scope:com.google.android.apps.exposurenotification.debug.TemporaryExposureKey)
  private static final com.google.android.apps.exposurenotification.proto.TemporaryExposureKey DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.android.apps.exposurenotification.proto.TemporaryExposureKey();
  }

  public static com.google.android.apps.exposurenotification.proto.TemporaryExposureKey getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<TemporaryExposureKey>
      PARSER = new com.google.protobuf.AbstractParser<TemporaryExposureKey>() {
    @java.lang.Override
    public TemporaryExposureKey parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TemporaryExposureKey(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TemporaryExposureKey> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TemporaryExposureKey> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.android.apps.exposurenotification.proto.TemporaryExposureKey getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

