// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: key_file.proto

package com.google.android.apps.exposurenotification.proto;

/**
 * <pre>
 * Protobuf definition for exports of confirmed temporary exposure keys.
 * These files have a 16-byte, zero-padded header before the protobuf data
 * starts. They will be contained in a zip archive, alongside a signature
 * file verifying the contents.
 * See https://static.googleusercontent.com/media/www.google.com/en//covid19/exposurenotifications/pdfs/Exposure-Key-File-Format-and-Verification.pdf
 * </pre>
 *
 * Protobuf type {@code com.google.android.apps.exposurenotification.debug.TemporaryExposureKeyExport}
 */
public  final class TemporaryExposureKeyExport extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.google.android.apps.exposurenotification.debug.TemporaryExposureKeyExport)
    TemporaryExposureKeyExportOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TemporaryExposureKeyExport.newBuilder() to construct.
  private TemporaryExposureKeyExport(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TemporaryExposureKeyExport() {
    region_ = "";
    signatureInfos_ = java.util.Collections.emptyList();
    keys_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TemporaryExposureKeyExport();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TemporaryExposureKeyExport(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {
            bitField0_ |= 0x00000001;
            startTimestamp_ = input.readFixed64();
            break;
          }
          case 17: {
            bitField0_ |= 0x00000002;
            endTimestamp_ = input.readFixed64();
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            region_ = bs;
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            batchNum_ = input.readInt32();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000010;
            batchSize_ = input.readInt32();
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) != 0)) {
              signatureInfos_ = new java.util.ArrayList<com.google.android.apps.exposurenotification.proto.SignatureInfo>();
              mutable_bitField0_ |= 0x00000020;
            }
            signatureInfos_.add(
                input.readMessage(com.google.android.apps.exposurenotification.proto.SignatureInfo.PARSER, extensionRegistry));
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000040) != 0)) {
              keys_ = new java.util.ArrayList<com.google.android.apps.exposurenotification.proto.TemporaryExposureKey>();
              mutable_bitField0_ |= 0x00000040;
            }
            keys_.add(
                input.readMessage(com.google.android.apps.exposurenotification.proto.TemporaryExposureKey.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000020) != 0)) {
        signatureInfos_ = java.util.Collections.unmodifiableList(signatureInfos_);
      }
      if (((mutable_bitField0_ & 0x00000040) != 0)) {
        keys_ = java.util.Collections.unmodifiableList(keys_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.android.apps.exposurenotification.proto.KeyFile.internal_static_com_google_android_apps_exposurenotification_debug_TemporaryExposureKeyExport_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.android.apps.exposurenotification.proto.KeyFile.internal_static_com_google_android_apps_exposurenotification_debug_TemporaryExposureKeyExport_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport.class, com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport.Builder.class);
  }

  private int bitField0_;
  public static final int START_TIMESTAMP_FIELD_NUMBER = 1;
  private long startTimestamp_;
  /**
   * <pre>
   * Time window of keys in this file based on arrival to server, in UTC
   * seconds
   * </pre>
   *
   * <code>optional fixed64 start_timestamp = 1;</code>
   * @return Whether the startTimestamp field is set.
   */
  public boolean hasStartTimestamp() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Time window of keys in this file based on arrival to server, in UTC
   * seconds
   * </pre>
   *
   * <code>optional fixed64 start_timestamp = 1;</code>
   * @return The startTimestamp.
   */
  public long getStartTimestamp() {
    return startTimestamp_;
  }

  public static final int END_TIMESTAMP_FIELD_NUMBER = 2;
  private long endTimestamp_;
  /**
   * <code>optional fixed64 end_timestamp = 2;</code>
   * @return Whether the endTimestamp field is set.
   */
  public boolean hasEndTimestamp() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional fixed64 end_timestamp = 2;</code>
   * @return The endTimestamp.
   */
  public long getEndTimestamp() {
    return endTimestamp_;
  }

  public static final int REGION_FIELD_NUMBER = 3;
  private volatile java.lang.Object region_;
  /**
   * <pre>
   * Region for which these keys came from (e.g., country)
   * </pre>
   *
   * <code>optional string region = 3;</code>
   * @return Whether the region field is set.
   */
  public boolean hasRegion() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * Region for which these keys came from (e.g., country)
   * </pre>
   *
   * <code>optional string region = 3;</code>
   * @return The region.
   */
  public java.lang.String getRegion() {
    java.lang.Object ref = region_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        region_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * Region for which these keys came from (e.g., country)
   * </pre>
   *
   * <code>optional string region = 3;</code>
   * @return The bytes for region.
   */
  public com.google.protobuf.ByteString
      getRegionBytes() {
    java.lang.Object ref = region_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      region_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BATCH_NUM_FIELD_NUMBER = 4;
  private int batchNum_;
  /**
   * <pre>
   * E.g., Batch 2 of 10. Ordinal, 1-based numbering.
   * Note: Not yet supported on iOS. Use values of 1 for both.
   * </pre>
   *
   * <code>optional int32 batch_num = 4;</code>
   * @return Whether the batchNum field is set.
   */
  public boolean hasBatchNum() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * E.g., Batch 2 of 10. Ordinal, 1-based numbering.
   * Note: Not yet supported on iOS. Use values of 1 for both.
   * </pre>
   *
   * <code>optional int32 batch_num = 4;</code>
   * @return The batchNum.
   */
  public int getBatchNum() {
    return batchNum_;
  }

  public static final int BATCH_SIZE_FIELD_NUMBER = 5;
  private int batchSize_;
  /**
   * <code>optional int32 batch_size = 5;</code>
   * @return Whether the batchSize field is set.
   */
  public boolean hasBatchSize() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional int32 batch_size = 5;</code>
   * @return The batchSize.
   */
  public int getBatchSize() {
    return batchSize_;
  }

  public static final int SIGNATURE_INFOS_FIELD_NUMBER = 6;
  private java.util.List<com.google.android.apps.exposurenotification.proto.SignatureInfo> signatureInfos_;
  /**
   * <pre>
   * Information about signatures
   * </pre>
   *
   * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
   */
  public java.util.List<com.google.android.apps.exposurenotification.proto.SignatureInfo> getSignatureInfosList() {
    return signatureInfos_;
  }
  /**
   * <pre>
   * Information about signatures
   * </pre>
   *
   * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
   */
  public java.util.List<? extends com.google.android.apps.exposurenotification.proto.SignatureInfoOrBuilder> 
      getSignatureInfosOrBuilderList() {
    return signatureInfos_;
  }
  /**
   * <pre>
   * Information about signatures
   * </pre>
   *
   * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
   */
  public int getSignatureInfosCount() {
    return signatureInfos_.size();
  }
  /**
   * <pre>
   * Information about signatures
   * </pre>
   *
   * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
   */
  public com.google.android.apps.exposurenotification.proto.SignatureInfo getSignatureInfos(int index) {
    return signatureInfos_.get(index);
  }
  /**
   * <pre>
   * Information about signatures
   * </pre>
   *
   * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
   */
  public com.google.android.apps.exposurenotification.proto.SignatureInfoOrBuilder getSignatureInfosOrBuilder(
      int index) {
    return signatureInfos_.get(index);
  }

  public static final int KEYS_FIELD_NUMBER = 7;
  private java.util.List<com.google.android.apps.exposurenotification.proto.TemporaryExposureKey> keys_;
  /**
   * <pre>
   * The TemporaryExposureKeys themselves
   * </pre>
   *
   * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
   */
  public java.util.List<com.google.android.apps.exposurenotification.proto.TemporaryExposureKey> getKeysList() {
    return keys_;
  }
  /**
   * <pre>
   * The TemporaryExposureKeys themselves
   * </pre>
   *
   * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
   */
  public java.util.List<? extends com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyOrBuilder> 
      getKeysOrBuilderList() {
    return keys_;
  }
  /**
   * <pre>
   * The TemporaryExposureKeys themselves
   * </pre>
   *
   * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
   */
  public int getKeysCount() {
    return keys_.size();
  }
  /**
   * <pre>
   * The TemporaryExposureKeys themselves
   * </pre>
   *
   * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
   */
  public com.google.android.apps.exposurenotification.proto.TemporaryExposureKey getKeys(int index) {
    return keys_.get(index);
  }
  /**
   * <pre>
   * The TemporaryExposureKeys themselves
   * </pre>
   *
   * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
   */
  public com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyOrBuilder getKeysOrBuilder(
      int index) {
    return keys_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeFixed64(1, startTimestamp_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeFixed64(2, endTimestamp_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, region_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt32(4, batchNum_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt32(5, batchSize_);
    }
    for (int i = 0; i < signatureInfos_.size(); i++) {
      output.writeMessage(6, signatureInfos_.get(i));
    }
    for (int i = 0; i < keys_.size(); i++) {
      output.writeMessage(7, keys_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed64Size(1, startTimestamp_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed64Size(2, endTimestamp_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, region_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, batchNum_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, batchSize_);
    }
    for (int i = 0; i < signatureInfos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, signatureInfos_.get(i));
    }
    for (int i = 0; i < keys_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, keys_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport)) {
      return super.equals(obj);
    }
    com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport other = (com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport) obj;

    if (hasStartTimestamp() != other.hasStartTimestamp()) return false;
    if (hasStartTimestamp()) {
      if (getStartTimestamp()
          != other.getStartTimestamp()) return false;
    }
    if (hasEndTimestamp() != other.hasEndTimestamp()) return false;
    if (hasEndTimestamp()) {
      if (getEndTimestamp()
          != other.getEndTimestamp()) return false;
    }
    if (hasRegion() != other.hasRegion()) return false;
    if (hasRegion()) {
      if (!getRegion()
          .equals(other.getRegion())) return false;
    }
    if (hasBatchNum() != other.hasBatchNum()) return false;
    if (hasBatchNum()) {
      if (getBatchNum()
          != other.getBatchNum()) return false;
    }
    if (hasBatchSize() != other.hasBatchSize()) return false;
    if (hasBatchSize()) {
      if (getBatchSize()
          != other.getBatchSize()) return false;
    }
    if (!getSignatureInfosList()
        .equals(other.getSignatureInfosList())) return false;
    if (!getKeysList()
        .equals(other.getKeysList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStartTimestamp()) {
      hash = (37 * hash) + START_TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStartTimestamp());
    }
    if (hasEndTimestamp()) {
      hash = (37 * hash) + END_TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEndTimestamp());
    }
    if (hasRegion()) {
      hash = (37 * hash) + REGION_FIELD_NUMBER;
      hash = (53 * hash) + getRegion().hashCode();
    }
    if (hasBatchNum()) {
      hash = (37 * hash) + BATCH_NUM_FIELD_NUMBER;
      hash = (53 * hash) + getBatchNum();
    }
    if (hasBatchSize()) {
      hash = (37 * hash) + BATCH_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getBatchSize();
    }
    if (getSignatureInfosCount() > 0) {
      hash = (37 * hash) + SIGNATURE_INFOS_FIELD_NUMBER;
      hash = (53 * hash) + getSignatureInfosList().hashCode();
    }
    if (getKeysCount() > 0) {
      hash = (37 * hash) + KEYS_FIELD_NUMBER;
      hash = (53 * hash) + getKeysList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Protobuf definition for exports of confirmed temporary exposure keys.
   * These files have a 16-byte, zero-padded header before the protobuf data
   * starts. They will be contained in a zip archive, alongside a signature
   * file verifying the contents.
   * See https://static.googleusercontent.com/media/www.google.com/en//covid19/exposurenotifications/pdfs/Exposure-Key-File-Format-and-Verification.pdf
   * </pre>
   *
   * Protobuf type {@code com.google.android.apps.exposurenotification.debug.TemporaryExposureKeyExport}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.google.android.apps.exposurenotification.debug.TemporaryExposureKeyExport)
      com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExportOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.android.apps.exposurenotification.proto.KeyFile.internal_static_com_google_android_apps_exposurenotification_debug_TemporaryExposureKeyExport_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.android.apps.exposurenotification.proto.KeyFile.internal_static_com_google_android_apps_exposurenotification_debug_TemporaryExposureKeyExport_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport.class, com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport.Builder.class);
    }

    // Construct using com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSignatureInfosFieldBuilder();
        getKeysFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      startTimestamp_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      endTimestamp_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      region_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      batchNum_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      batchSize_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      if (signatureInfosBuilder_ == null) {
        signatureInfos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        signatureInfosBuilder_.clear();
      }
      if (keysBuilder_ == null) {
        keys_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
      } else {
        keysBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.android.apps.exposurenotification.proto.KeyFile.internal_static_com_google_android_apps_exposurenotification_debug_TemporaryExposureKeyExport_descriptor;
    }

    @java.lang.Override
    public com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport getDefaultInstanceForType() {
      return com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport build() {
      com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport buildPartial() {
      com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport result = new com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.startTimestamp_ = startTimestamp_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.endTimestamp_ = endTimestamp_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.region_ = region_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.batchNum_ = batchNum_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.batchSize_ = batchSize_;
        to_bitField0_ |= 0x00000010;
      }
      if (signatureInfosBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          signatureInfos_ = java.util.Collections.unmodifiableList(signatureInfos_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.signatureInfos_ = signatureInfos_;
      } else {
        result.signatureInfos_ = signatureInfosBuilder_.build();
      }
      if (keysBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0)) {
          keys_ = java.util.Collections.unmodifiableList(keys_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.keys_ = keys_;
      } else {
        result.keys_ = keysBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport) {
        return mergeFrom((com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport other) {
      if (other == com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport.getDefaultInstance()) return this;
      if (other.hasStartTimestamp()) {
        setStartTimestamp(other.getStartTimestamp());
      }
      if (other.hasEndTimestamp()) {
        setEndTimestamp(other.getEndTimestamp());
      }
      if (other.hasRegion()) {
        bitField0_ |= 0x00000004;
        region_ = other.region_;
        onChanged();
      }
      if (other.hasBatchNum()) {
        setBatchNum(other.getBatchNum());
      }
      if (other.hasBatchSize()) {
        setBatchSize(other.getBatchSize());
      }
      if (signatureInfosBuilder_ == null) {
        if (!other.signatureInfos_.isEmpty()) {
          if (signatureInfos_.isEmpty()) {
            signatureInfos_ = other.signatureInfos_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureSignatureInfosIsMutable();
            signatureInfos_.addAll(other.signatureInfos_);
          }
          onChanged();
        }
      } else {
        if (!other.signatureInfos_.isEmpty()) {
          if (signatureInfosBuilder_.isEmpty()) {
            signatureInfosBuilder_.dispose();
            signatureInfosBuilder_ = null;
            signatureInfos_ = other.signatureInfos_;
            bitField0_ = (bitField0_ & ~0x00000020);
            signatureInfosBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSignatureInfosFieldBuilder() : null;
          } else {
            signatureInfosBuilder_.addAllMessages(other.signatureInfos_);
          }
        }
      }
      if (keysBuilder_ == null) {
        if (!other.keys_.isEmpty()) {
          if (keys_.isEmpty()) {
            keys_ = other.keys_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureKeysIsMutable();
            keys_.addAll(other.keys_);
          }
          onChanged();
        }
      } else {
        if (!other.keys_.isEmpty()) {
          if (keysBuilder_.isEmpty()) {
            keysBuilder_.dispose();
            keysBuilder_ = null;
            keys_ = other.keys_;
            bitField0_ = (bitField0_ & ~0x00000040);
            keysBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getKeysFieldBuilder() : null;
          } else {
            keysBuilder_.addAllMessages(other.keys_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long startTimestamp_ ;
    /**
     * <pre>
     * Time window of keys in this file based on arrival to server, in UTC
     * seconds
     * </pre>
     *
     * <code>optional fixed64 start_timestamp = 1;</code>
     * @return Whether the startTimestamp field is set.
     */
    public boolean hasStartTimestamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Time window of keys in this file based on arrival to server, in UTC
     * seconds
     * </pre>
     *
     * <code>optional fixed64 start_timestamp = 1;</code>
     * @return The startTimestamp.
     */
    public long getStartTimestamp() {
      return startTimestamp_;
    }
    /**
     * <pre>
     * Time window of keys in this file based on arrival to server, in UTC
     * seconds
     * </pre>
     *
     * <code>optional fixed64 start_timestamp = 1;</code>
     * @param value The startTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setStartTimestamp(long value) {
      bitField0_ |= 0x00000001;
      startTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Time window of keys in this file based on arrival to server, in UTC
     * seconds
     * </pre>
     *
     * <code>optional fixed64 start_timestamp = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000001);
      startTimestamp_ = 0L;
      onChanged();
      return this;
    }

    private long endTimestamp_ ;
    /**
     * <code>optional fixed64 end_timestamp = 2;</code>
     * @return Whether the endTimestamp field is set.
     */
    public boolean hasEndTimestamp() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional fixed64 end_timestamp = 2;</code>
     * @return The endTimestamp.
     */
    public long getEndTimestamp() {
      return endTimestamp_;
    }
    /**
     * <code>optional fixed64 end_timestamp = 2;</code>
     * @param value The endTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setEndTimestamp(long value) {
      bitField0_ |= 0x00000002;
      endTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional fixed64 end_timestamp = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000002);
      endTimestamp_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object region_ = "";
    /**
     * <pre>
     * Region for which these keys came from (e.g., country)
     * </pre>
     *
     * <code>optional string region = 3;</code>
     * @return Whether the region field is set.
     */
    public boolean hasRegion() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Region for which these keys came from (e.g., country)
     * </pre>
     *
     * <code>optional string region = 3;</code>
     * @return The region.
     */
    public java.lang.String getRegion() {
      java.lang.Object ref = region_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          region_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Region for which these keys came from (e.g., country)
     * </pre>
     *
     * <code>optional string region = 3;</code>
     * @return The bytes for region.
     */
    public com.google.protobuf.ByteString
        getRegionBytes() {
      java.lang.Object ref = region_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        region_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Region for which these keys came from (e.g., country)
     * </pre>
     *
     * <code>optional string region = 3;</code>
     * @param value The region to set.
     * @return This builder for chaining.
     */
    public Builder setRegion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      region_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Region for which these keys came from (e.g., country)
     * </pre>
     *
     * <code>optional string region = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRegion() {
      bitField0_ = (bitField0_ & ~0x00000004);
      region_ = getDefaultInstance().getRegion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Region for which these keys came from (e.g., country)
     * </pre>
     *
     * <code>optional string region = 3;</code>
     * @param value The bytes for region to set.
     * @return This builder for chaining.
     */
    public Builder setRegionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      region_ = value;
      onChanged();
      return this;
    }

    private int batchNum_ ;
    /**
     * <pre>
     * E.g., Batch 2 of 10. Ordinal, 1-based numbering.
     * Note: Not yet supported on iOS. Use values of 1 for both.
     * </pre>
     *
     * <code>optional int32 batch_num = 4;</code>
     * @return Whether the batchNum field is set.
     */
    public boolean hasBatchNum() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * E.g., Batch 2 of 10. Ordinal, 1-based numbering.
     * Note: Not yet supported on iOS. Use values of 1 for both.
     * </pre>
     *
     * <code>optional int32 batch_num = 4;</code>
     * @return The batchNum.
     */
    public int getBatchNum() {
      return batchNum_;
    }
    /**
     * <pre>
     * E.g., Batch 2 of 10. Ordinal, 1-based numbering.
     * Note: Not yet supported on iOS. Use values of 1 for both.
     * </pre>
     *
     * <code>optional int32 batch_num = 4;</code>
     * @param value The batchNum to set.
     * @return This builder for chaining.
     */
    public Builder setBatchNum(int value) {
      bitField0_ |= 0x00000008;
      batchNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * E.g., Batch 2 of 10. Ordinal, 1-based numbering.
     * Note: Not yet supported on iOS. Use values of 1 for both.
     * </pre>
     *
     * <code>optional int32 batch_num = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBatchNum() {
      bitField0_ = (bitField0_ & ~0x00000008);
      batchNum_ = 0;
      onChanged();
      return this;
    }

    private int batchSize_ ;
    /**
     * <code>optional int32 batch_size = 5;</code>
     * @return Whether the batchSize field is set.
     */
    public boolean hasBatchSize() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 batch_size = 5;</code>
     * @return The batchSize.
     */
    public int getBatchSize() {
      return batchSize_;
    }
    /**
     * <code>optional int32 batch_size = 5;</code>
     * @param value The batchSize to set.
     * @return This builder for chaining.
     */
    public Builder setBatchSize(int value) {
      bitField0_ |= 0x00000010;
      batchSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 batch_size = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearBatchSize() {
      bitField0_ = (bitField0_ & ~0x00000010);
      batchSize_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.google.android.apps.exposurenotification.proto.SignatureInfo> signatureInfos_ =
      java.util.Collections.emptyList();
    private void ensureSignatureInfosIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        signatureInfos_ = new java.util.ArrayList<com.google.android.apps.exposurenotification.proto.SignatureInfo>(signatureInfos_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.android.apps.exposurenotification.proto.SignatureInfo, com.google.android.apps.exposurenotification.proto.SignatureInfo.Builder, com.google.android.apps.exposurenotification.proto.SignatureInfoOrBuilder> signatureInfosBuilder_;

    /**
     * <pre>
     * Information about signatures
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
     */
    public java.util.List<com.google.android.apps.exposurenotification.proto.SignatureInfo> getSignatureInfosList() {
      if (signatureInfosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(signatureInfos_);
      } else {
        return signatureInfosBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Information about signatures
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
     */
    public int getSignatureInfosCount() {
      if (signatureInfosBuilder_ == null) {
        return signatureInfos_.size();
      } else {
        return signatureInfosBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Information about signatures
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
     */
    public com.google.android.apps.exposurenotification.proto.SignatureInfo getSignatureInfos(int index) {
      if (signatureInfosBuilder_ == null) {
        return signatureInfos_.get(index);
      } else {
        return signatureInfosBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Information about signatures
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
     */
    public Builder setSignatureInfos(
        int index, com.google.android.apps.exposurenotification.proto.SignatureInfo value) {
      if (signatureInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSignatureInfosIsMutable();
        signatureInfos_.set(index, value);
        onChanged();
      } else {
        signatureInfosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Information about signatures
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
     */
    public Builder setSignatureInfos(
        int index, com.google.android.apps.exposurenotification.proto.SignatureInfo.Builder builderForValue) {
      if (signatureInfosBuilder_ == null) {
        ensureSignatureInfosIsMutable();
        signatureInfos_.set(index, builderForValue.build());
        onChanged();
      } else {
        signatureInfosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Information about signatures
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
     */
    public Builder addSignatureInfos(com.google.android.apps.exposurenotification.proto.SignatureInfo value) {
      if (signatureInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSignatureInfosIsMutable();
        signatureInfos_.add(value);
        onChanged();
      } else {
        signatureInfosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Information about signatures
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
     */
    public Builder addSignatureInfos(
        int index, com.google.android.apps.exposurenotification.proto.SignatureInfo value) {
      if (signatureInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSignatureInfosIsMutable();
        signatureInfos_.add(index, value);
        onChanged();
      } else {
        signatureInfosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Information about signatures
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
     */
    public Builder addSignatureInfos(
        com.google.android.apps.exposurenotification.proto.SignatureInfo.Builder builderForValue) {
      if (signatureInfosBuilder_ == null) {
        ensureSignatureInfosIsMutable();
        signatureInfos_.add(builderForValue.build());
        onChanged();
      } else {
        signatureInfosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Information about signatures
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
     */
    public Builder addSignatureInfos(
        int index, com.google.android.apps.exposurenotification.proto.SignatureInfo.Builder builderForValue) {
      if (signatureInfosBuilder_ == null) {
        ensureSignatureInfosIsMutable();
        signatureInfos_.add(index, builderForValue.build());
        onChanged();
      } else {
        signatureInfosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Information about signatures
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
     */
    public Builder addAllSignatureInfos(
        java.lang.Iterable<? extends com.google.android.apps.exposurenotification.proto.SignatureInfo> values) {
      if (signatureInfosBuilder_ == null) {
        ensureSignatureInfosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, signatureInfos_);
        onChanged();
      } else {
        signatureInfosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Information about signatures
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
     */
    public Builder clearSignatureInfos() {
      if (signatureInfosBuilder_ == null) {
        signatureInfos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        signatureInfosBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Information about signatures
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
     */
    public Builder removeSignatureInfos(int index) {
      if (signatureInfosBuilder_ == null) {
        ensureSignatureInfosIsMutable();
        signatureInfos_.remove(index);
        onChanged();
      } else {
        signatureInfosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Information about signatures
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
     */
    public com.google.android.apps.exposurenotification.proto.SignatureInfo.Builder getSignatureInfosBuilder(
        int index) {
      return getSignatureInfosFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Information about signatures
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
     */
    public com.google.android.apps.exposurenotification.proto.SignatureInfoOrBuilder getSignatureInfosOrBuilder(
        int index) {
      if (signatureInfosBuilder_ == null) {
        return signatureInfos_.get(index);  } else {
        return signatureInfosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Information about signatures
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
     */
    public java.util.List<? extends com.google.android.apps.exposurenotification.proto.SignatureInfoOrBuilder> 
         getSignatureInfosOrBuilderList() {
      if (signatureInfosBuilder_ != null) {
        return signatureInfosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(signatureInfos_);
      }
    }
    /**
     * <pre>
     * Information about signatures
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
     */
    public com.google.android.apps.exposurenotification.proto.SignatureInfo.Builder addSignatureInfosBuilder() {
      return getSignatureInfosFieldBuilder().addBuilder(
          com.google.android.apps.exposurenotification.proto.SignatureInfo.getDefaultInstance());
    }
    /**
     * <pre>
     * Information about signatures
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
     */
    public com.google.android.apps.exposurenotification.proto.SignatureInfo.Builder addSignatureInfosBuilder(
        int index) {
      return getSignatureInfosFieldBuilder().addBuilder(
          index, com.google.android.apps.exposurenotification.proto.SignatureInfo.getDefaultInstance());
    }
    /**
     * <pre>
     * Information about signatures
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.SignatureInfo signature_infos = 6;</code>
     */
    public java.util.List<com.google.android.apps.exposurenotification.proto.SignatureInfo.Builder> 
         getSignatureInfosBuilderList() {
      return getSignatureInfosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.android.apps.exposurenotification.proto.SignatureInfo, com.google.android.apps.exposurenotification.proto.SignatureInfo.Builder, com.google.android.apps.exposurenotification.proto.SignatureInfoOrBuilder> 
        getSignatureInfosFieldBuilder() {
      if (signatureInfosBuilder_ == null) {
        signatureInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.android.apps.exposurenotification.proto.SignatureInfo, com.google.android.apps.exposurenotification.proto.SignatureInfo.Builder, com.google.android.apps.exposurenotification.proto.SignatureInfoOrBuilder>(
                signatureInfos_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        signatureInfos_ = null;
      }
      return signatureInfosBuilder_;
    }

    private java.util.List<com.google.android.apps.exposurenotification.proto.TemporaryExposureKey> keys_ =
      java.util.Collections.emptyList();
    private void ensureKeysIsMutable() {
      if (!((bitField0_ & 0x00000040) != 0)) {
        keys_ = new java.util.ArrayList<com.google.android.apps.exposurenotification.proto.TemporaryExposureKey>(keys_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.android.apps.exposurenotification.proto.TemporaryExposureKey, com.google.android.apps.exposurenotification.proto.TemporaryExposureKey.Builder, com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyOrBuilder> keysBuilder_;

    /**
     * <pre>
     * The TemporaryExposureKeys themselves
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
     */
    public java.util.List<com.google.android.apps.exposurenotification.proto.TemporaryExposureKey> getKeysList() {
      if (keysBuilder_ == null) {
        return java.util.Collections.unmodifiableList(keys_);
      } else {
        return keysBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The TemporaryExposureKeys themselves
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
     */
    public int getKeysCount() {
      if (keysBuilder_ == null) {
        return keys_.size();
      } else {
        return keysBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The TemporaryExposureKeys themselves
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
     */
    public com.google.android.apps.exposurenotification.proto.TemporaryExposureKey getKeys(int index) {
      if (keysBuilder_ == null) {
        return keys_.get(index);
      } else {
        return keysBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The TemporaryExposureKeys themselves
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
     */
    public Builder setKeys(
        int index, com.google.android.apps.exposurenotification.proto.TemporaryExposureKey value) {
      if (keysBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeysIsMutable();
        keys_.set(index, value);
        onChanged();
      } else {
        keysBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The TemporaryExposureKeys themselves
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
     */
    public Builder setKeys(
        int index, com.google.android.apps.exposurenotification.proto.TemporaryExposureKey.Builder builderForValue) {
      if (keysBuilder_ == null) {
        ensureKeysIsMutable();
        keys_.set(index, builderForValue.build());
        onChanged();
      } else {
        keysBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The TemporaryExposureKeys themselves
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
     */
    public Builder addKeys(com.google.android.apps.exposurenotification.proto.TemporaryExposureKey value) {
      if (keysBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeysIsMutable();
        keys_.add(value);
        onChanged();
      } else {
        keysBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The TemporaryExposureKeys themselves
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
     */
    public Builder addKeys(
        int index, com.google.android.apps.exposurenotification.proto.TemporaryExposureKey value) {
      if (keysBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeysIsMutable();
        keys_.add(index, value);
        onChanged();
      } else {
        keysBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The TemporaryExposureKeys themselves
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
     */
    public Builder addKeys(
        com.google.android.apps.exposurenotification.proto.TemporaryExposureKey.Builder builderForValue) {
      if (keysBuilder_ == null) {
        ensureKeysIsMutable();
        keys_.add(builderForValue.build());
        onChanged();
      } else {
        keysBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The TemporaryExposureKeys themselves
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
     */
    public Builder addKeys(
        int index, com.google.android.apps.exposurenotification.proto.TemporaryExposureKey.Builder builderForValue) {
      if (keysBuilder_ == null) {
        ensureKeysIsMutable();
        keys_.add(index, builderForValue.build());
        onChanged();
      } else {
        keysBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The TemporaryExposureKeys themselves
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
     */
    public Builder addAllKeys(
        java.lang.Iterable<? extends com.google.android.apps.exposurenotification.proto.TemporaryExposureKey> values) {
      if (keysBuilder_ == null) {
        ensureKeysIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, keys_);
        onChanged();
      } else {
        keysBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The TemporaryExposureKeys themselves
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
     */
    public Builder clearKeys() {
      if (keysBuilder_ == null) {
        keys_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        keysBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The TemporaryExposureKeys themselves
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
     */
    public Builder removeKeys(int index) {
      if (keysBuilder_ == null) {
        ensureKeysIsMutable();
        keys_.remove(index);
        onChanged();
      } else {
        keysBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The TemporaryExposureKeys themselves
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
     */
    public com.google.android.apps.exposurenotification.proto.TemporaryExposureKey.Builder getKeysBuilder(
        int index) {
      return getKeysFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The TemporaryExposureKeys themselves
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
     */
    public com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyOrBuilder getKeysOrBuilder(
        int index) {
      if (keysBuilder_ == null) {
        return keys_.get(index);  } else {
        return keysBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The TemporaryExposureKeys themselves
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
     */
    public java.util.List<? extends com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyOrBuilder> 
         getKeysOrBuilderList() {
      if (keysBuilder_ != null) {
        return keysBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(keys_);
      }
    }
    /**
     * <pre>
     * The TemporaryExposureKeys themselves
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
     */
    public com.google.android.apps.exposurenotification.proto.TemporaryExposureKey.Builder addKeysBuilder() {
      return getKeysFieldBuilder().addBuilder(
          com.google.android.apps.exposurenotification.proto.TemporaryExposureKey.getDefaultInstance());
    }
    /**
     * <pre>
     * The TemporaryExposureKeys themselves
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
     */
    public com.google.android.apps.exposurenotification.proto.TemporaryExposureKey.Builder addKeysBuilder(
        int index) {
      return getKeysFieldBuilder().addBuilder(
          index, com.google.android.apps.exposurenotification.proto.TemporaryExposureKey.getDefaultInstance());
    }
    /**
     * <pre>
     * The TemporaryExposureKeys themselves
     * </pre>
     *
     * <code>repeated .com.google.android.apps.exposurenotification.debug.TemporaryExposureKey keys = 7;</code>
     */
    public java.util.List<com.google.android.apps.exposurenotification.proto.TemporaryExposureKey.Builder> 
         getKeysBuilderList() {
      return getKeysFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.android.apps.exposurenotification.proto.TemporaryExposureKey, com.google.android.apps.exposurenotification.proto.TemporaryExposureKey.Builder, com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyOrBuilder> 
        getKeysFieldBuilder() {
      if (keysBuilder_ == null) {
        keysBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.android.apps.exposurenotification.proto.TemporaryExposureKey, com.google.android.apps.exposurenotification.proto.TemporaryExposureKey.Builder, com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyOrBuilder>(
                keys_,
                ((bitField0_ & 0x00000040) != 0),
                getParentForChildren(),
                isClean());
        keys_ = null;
      }
      return keysBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.google.android.apps.exposurenotification.debug.TemporaryExposureKeyExport)
  }

  // @@protoc_insertion_point(class_scope:com.google.android.apps.exposurenotification.debug.TemporaryExposureKeyExport)
  private static final com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport();
  }

  public static com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<TemporaryExposureKeyExport>
      PARSER = new com.google.protobuf.AbstractParser<TemporaryExposureKeyExport>() {
    @java.lang.Override
    public TemporaryExposureKeyExport parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TemporaryExposureKeyExport(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TemporaryExposureKeyExport> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TemporaryExposureKeyExport> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.android.apps.exposurenotification.proto.TemporaryExposureKeyExport getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

